name: inJaus
title: inJaus | #EmpiezaLaRevolución
description: inJaus es una iniciativa que soporta proyectos que quieran cambiar el mundo, para mejor.
tags:
  - inUtil ffa
  - inBu
  - inUtil edge
  - Herminia
  - internet distrubuida
email: info@injaus.eu
disqus_username: disqus_username
show_hero: true
menu:
  - title: Home
    url: /
  - title: Manifesto
    url: /manifesto
  - title: ¿Quiénes somos?
    url: /staff
  - title: Sobre nosotros
    url: /about
  - title: Contacta
    url: /contact
  - title: Feed RSS
    url: /feed.xml
paginate: 6

